project:
  type: website

website:
  title: "BOKU Exams"
  page-footer:
    center: "<b>This documentation is currently in development and not complete. Please provide feedback on Github Discussions by clicking on the Github icon on the top left. </b>"
    background: info
    

  sidebar:
    style: "docked"
    background: light
    search: true
    pinned: true
    contents:
      - href: index.qmd
        text: Home
      - href: readme.qmd
        text: README
      - href: ideas.qmd
        text: Notes
      - href: first-steps.qmd
        text: First Steps 
      - href: r-exams.qmd
        text: R and R/exams Info
      - href: setup.qmd
        text: Project Setup
      
      - section: .Rmd-file
        contents: 
        - href: structure-Rmd.qmd
          text: Structure
        - href: creation-Rmd.qmd
          text: Creation 
        - href: conversion.qmd
        - text: Conversion 
          
      - section: Add-ons 
        contents: 
        - href: add-ons.qmd
          text: Add-ons to .Rmd-files
          
      - href: moodle.qmd
        text: Moodle Upload 
            
        
      - section:  Basic Examples 
        contents: 
        - href: example1.qmd
          text: Numeric Example
        - href: example2.qmd
          text: String Example 
        - href: example3.qmd 
          text: Single Choice Example 
        - href: example4.qmd 
          text: Multiple Choice Example
          
      - section: Advanced Examples 
        contents: 
        - href: advanced1.qmd
          text: Example 1
        - href: advanced2.qmd
          text: Example 2 
          
      - href: ref.qmd 
        text: Further References
        
      - href: faq.qmd 
        text: FAQ

      - href: templates.qmd 
        text: Downloads and Custom Template Creation 
        
        
        
        
    tools:
    - icon: github
      menu:
        - text: Source Code
          href: https://github.com/boku-stat/BOKU-Exams-Documentation
        - text: Provide Feedback
          href: https://github.com/boku-stat/BOKU-Exams-Documentation/discussions
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: source

