project:
  type: website

website:
  title: "BOKU Exams"
  sidebar:
    style: "docked"
    background: light
    search: true
    pinned: true
    contents:
      - href: index.qmd
        text: Home
      - href: ideas.qmd
        text: Ideas
      - section: Rmd-file
        contents: 
        - href: structure-Rmd.qmd
          text: Structure
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

