---
title: "FAQ"
---

This will describe frequently asked questions and common mistakes.

# General Questions 

::: {.callout-note title="What is `R/exams`" collapse="true"}
`R/exams` is an R package, which allows for dynamic exam creation. Exam questions can have many formats and can easily be individualized. For more information about `R/exams` see [here](r-exams.qmd) and for a brief introduction to the concept see [here](first-steps.qmd)
::: 

::: {.callout-note title="Who is this documentation intended for?" collapse="true"}
Anyone who wants to create dynamic exercises for their own course, using a similar system as the one that is currently used for the Statistics courses. 
::: 

::: {.callout-note title="Do you need prior experience with R?" collapse="true"}
It depends, but it can be done without. Without any prior experiencing with any programming language, the learning curve can be a bit steep. However, R and also `R/exams` is documented very well and there are many examples and templates available. Simpler examples are created very easily and since the structure always remains the same, building more complex examples can be done step-by-step. 
::: 

::: {.callout-note title="Does the course need to teach R and/or statistics?" collapse="true"}
No, R is just the software to create the exams, however the content is completely adjustable. There are different formats available, see several [basic](example1.qmd) and [advanced](advanced1.qmd) examples. 
::: 

# Installation  

::: {.callout-note title="How do I install R and RStudio?" collapse="true"}
The software can be downloaded and simply installed following the instructions. More information can be found [here](r-exams.qmd). 

Download R [here from CRAN](https://cran.r-project.org). 

Download Rstudio [here](https://posit.co/download/rstudio-desktop/).

An installation guide can be found [here](https://www.r-exams.org/tutorials/installation/)

A step-by-step installation tutorial by the Statistics Institute at BOKU can be found [here](https://statistik.boku.ac.at/stat-lehre/doku.php?id=statistik_mit_r:rstudio:rstudio_installation:start)
::: 

::: {.callout-note title="How do I install `R/exams`" collapse="true"}
Once R and RStudio are installed, `R/exams` can simply installed by running the following code lines in the console or in a script. `library()` is used to load the content of the exams package. 

```R 
install.packages("exams") # installs the package, note the quotes!!  
library(exams) # loads the content of the package 
```
::: 

::: {.callout-note title="Do I need other software?" collapse="true"}
When converting exams to pdf format, a LaTeX installation is required. One can be installed using the package `tinytex`. 
```R
tinytex::install_tinytex() #function from tinytex 
``` 
Additionally, for markdown exercises, Pandoc is required, however this automatically comes with the installation of RStudio. 
:::  


# Setup 

::: {.callout-note title="How and why should I setup an R project?" collapse="true"}
R projects can be used for organizing and working with several files in an easy and efficient way. See [here](setup.qmd) for an explanation on how to setup the project. 
::: 

::: {.callout-note title="How can I create an .R or .Rmd file?" collapse="true"}
See [this page](setup.qmd) for a step-by-step guide. 
::: 

# Creating Exercises 

::: {.callout-note title="What file-formats are used?" collapse="true"}
The questions and solutions are stored in an .Rmd-file, which is an R markdown file. The script for conversion is stored in an .R-file. Both can be created and edited within RStudio. 
::: 

::: {.callout-note title="What question types are available?" collapse="true"}
The most common types are "numeric", "string" (for word-based answers), "single choice" and "multiple choice". Others are also available, depending on the output format. A combination of any of these is of the type "cloze". 
::: 

::: {.callout-note title="How do I add mathematical formulas to my question/solution?" collapse="true"}
Using `$...$`for inline mathematical notation and `$$...$$`for centered notation. 
For example: The following line 
```markdown 
$\alpha = \frac{1}{100}$
```
produces this: $\alpha = \frac{1}{100}$
::: 

::: {.callout-note title="How do I include a picture in my exercise?" collapse="true"} 
See the section about including pictures [here](add-ons.qmd#add-pcitures)
:::  

::: {.callout-note title="How do I embed a link in my exercise?" collapse="true"}

::: 

::: {.callout-note title="Where can I find a template?" collapse="true"}
Templates for both the .Rmd-file and the converison script can be found [here](templates.qmd). 
::: 

# Conversion and Output 

::: {.callout-note title="What are the available output formats?" collapse="true"}
The most common ones are PDF, HTML and .xml for the import in Moodle. However there are many more available see [here](https://www.r-exams.org/intro/oneforall/)
::: 

::: {.callout-note title="How do I generate an exam?" collapse="true"}
The conversion into the desired format is done by using a `exams2xyz()`function from the `R/exams` package. The process is explained in more detail on the [conversion page](conversion.qmd)
::: 

::: {.callout-note title="How can I upload my .xml-file to Moodle" collapse="true"}
See a step-by-step guide on [this page](moodle.qmd) on the upload to Moodle.
:::  

# Common Problems {#common-problems}

::: {.callout-note title="My code is not being recognized as code within the .Rmd-file." collapse="true"} 
It is necessary to mark the beginning and the end of the code chunk using three backticks (\`) and `{r}`. 

````markdown 
```{{r}}
# place code here
```
````
:::

::: {.callout-note title="The conversion to pdf format fails." collapse="true"}
Make sure to have LaTeX installed, see for example the package [`R/tinytex`](https://cran.r-project.org/package=tinytex)
::: 

::: {.callout-note title="Images do not appear correctly in my output." collapse="true"}

- Make sure the image is stored in the correct folder. 
- Use relative paths (./path_to_pic/picture.png). 
- Check whether `include_supplement()` is used correctly. 
::: 

# Advanced Options 

::: {.callout-note title="What other options do I have for costumization?" collapse="true"}

::: 

::: {.callout-note title="What other parameters can I set for conversion?" collapse="true"}

::: 

::: {.callout-note title="How can I grade the exams?" collapse="true"}
For Moodle exams, the settings for grading are within Moodle. 

For single/multiple choice questions, `exams2nops` can be used to create exercises on paper (NOPS format), which can then be scanned and graded automatically. See [here](https://www.r-exams.org/tutorials/exams2nops/) for more information. 
::: 


# Further Resources 

::: {.callout-note title="Where can I ask questions about this documentation?" collapse="true"}
See our discussion forum on Github [here](https://github.com/boku-stat/BOKU-Exams-Documentation/discussions)
::: 

::: {.callout-note title="Where do I find other resources for `R/exams`?" collapse="true"}
See [this page](ref.qmd) for a multitude of links for different topics regarding `R/exams`. 
::: 






