---
title: "Ideas"
---

This is the page for future ideas and important notes for documentation, for internal use. 

Notes, Stand 13.02 

Allgemein: 

- Internal Links 
- check use of backticks 
- Links to external doku formatierung ??? links oder beschreibung in den []() 
- Reihenfolge der Seiten? 
- Begriff: questions oder answers? -> questions 
- R code: formatiert mit Farben oder including knitr tags, zb auf structure .Rmd page (also direkt auf der Seite oder mit filter include)
- Advanced examples (mit cloze, csv files, data generation, stories etc. ??? )
- Auf moodle: interne doku und bsp aus statistik zur verfügung als advanced examples? 
- Soll folder structure (wurde nur bei Coaches verwendet) teil der doku sein bzw des how to? überhaupt notwendig? 

Shiny App: 

- weiter verfolgen? 
- hosten? wenn ja wo? (Quarto macht probleme), shinyapps.io? 
- nicht hosten? -> wie bekommt man zugriff dazu? 
- welche features? 
- gehört neu strukturiert und aufgesetzt mit (fast) allen features in mind 

Upload Moodle 

- seite erstellen 
- anleitung schreiben 

Home: 

- ~~Autoren~~ 
- Link zu Moodle Kurs 
- Lizenz? 
- ~~Read-me ?~~ 

First Steps: 

R-info: 

- Abschnitt über R/exams ausweiten, alle Autoren nennen 

Structure Rmd: 

- ~~template für download hinzufügen~~
- Code chunks anpassen, sodass knitr tags dabei sind (filter include-code-files verwenden!)
- Template verbessern: code chunks benennen, knitr tags 

Creation Rmd:

- umbenennen? 
- ~~fertig schreiben~~ 

Structure R: 

- ~~basic structure schreiben~~
- advanced structure schreiben 
- templates erstellen und einfügen 

Conversion: 

- ~~gehört in der form eigentlich in die interne doku~~ 
- basic method (basic umwandlung ohne "schnickschnack")
- advanced method (Lukas' script verallgemeinert)
- vielleicht zusammenlegen mit Strucutre R-file ? -> eher nein 


Add ons: 

- ~~Abschnitt über graphs hinzufügen und schreiben~~ 

Basic Examples: 

- final check, cross references 

Advanced Examples: 

- Seite erstellen 
- Examples ausdenken 
- Einfach nur zur homepage verlinken?? 

FAQ: 

- Fragen sammeln/ausdenken  
- Format für fragen überlegen (dropdown? callout chunks?)

References: 

- ~~Erste Quellen und Resourcen zusammentragen~~ 
- weitere Abschnitte/Themenbereiche überlegen 
- zu diesen weitere Quellen suchen 



Further Notes: 

- Internal references: <https://machow.github.io/quartodoc/get-started/interlinks.html>

-   How to include r markdown chunks (which are not executable)

    -   <https://quarto.org/docs/authoring/markdown-basics.html#source-code>

-   include r chunks with visible settings

-   ~~README? recommended order of reading documentation~~

-   If a document contains no R code chunks, the default inline syntax using curly braces, e. g. `` `{r}` ``, will not work. Instead, the engine must be set to knitr in the YAML header like this: `engine: knitr`, and no curly braces must be used in the inline code: `` `r` ``.[^1]

[^1]: <https://stackoverflow.com/questions/78569518/why-is-r-inline-code-not-executed-in-quarto-in-some-situations>

Writing style (internal)

-   Functions are written with () at the end and in backticks. Example: `answerlist()`

-   Backticks `test` for all R objects. Examples: `questions`, `TRUE`
