---
title: "R, RStudio and R/exams"
---

This page gives a bit more information about R, RStudio and R/exams, however in general the documentation focuses on the parts of R/exams that are relevant for creating the exams like it is done at BOKU. It is by no mean comprehensive and there already exists a lot of much more comprehensive documentation for R, RStudio and R/exams.

# R

R is an open source software and freely available for all common platforms. It has many statistical applications, but is also used in various other fields. There are many extra packages that can easily be installed from CRAN (Comprehensive R Archive Network), where a lot of packages are maintained.

Download R [here from CRAN](https://cran.r-project.org).

See [how to install R and RStudio](https://statistik.boku.ac.at/stat-lehre/doku.php?id=statistik_mit_r:rstudio:rstudio_installation:start).

How to install packages like `R/exams:`

``` r
install.packages("package_name") #insert the name of the package instead of package_name

install.packages("exams") #install the exams package 
library(exams) #loads the contents of the package to make them available 
```

# RStudio

RStudio is an integrated development environment (IDE) for R. An IDE is useful for writing and editing code, as it includes additional windows besides the console where both code and results are printed, such as an editing window, a help page, a viewer for plots and many more. All in all, it makes writing in R more comfortable and helps to keep an overview.

Download Rstudio [here](https://posit.co/download/rstudio-desktop/).

# R/exams

The R/exams package is used for automatically generating and evaluating exams. It was developed by Bettina Grün and Achim Zeileis. Other contributors are: Friedrich Leisch, Nikolaus Umlauf, Mirko Birbaumer, Dominik Ernst, Patrik Keller, Niels Smits, Reto Stauffer, Kenji Sato and Florian Wickelmaier. 

It can be found at CRAN [here](https://cran.r-project.org/package=exams).
